- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
- name: Add Docker repository
  cmd: "yum-config-manager --add-repo {{docker_repo}}"
- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes
