- name: Setup HTTP instance
  become: yes
  containers.podman.podman_container:
    name: static
    image: docker.io/nginx
    env:
      VIRTUAL_HOST: "static.younes"
      LETSENCRYPT_HOST: "static.younes"
- name: Add instance to Systemd
  become: yes
  vars:
    name: instance
    description: Test HTTP instance
  template:
    src: podman.service.j2
    dest: /etc/systemd/system/test.service
    owner: root
    group: root
    mode: 644

