- name: Install Podman
  become: yes
  dnf:
    name: podman
    state: latest
- name: Setup NGiNX reverse proxy
  become: yes
  containers.podman.podman_container:
    name: proxy
    image: jwilder/nginx-proxy
    tty: yes
    publish:
      - 80:80
      - 443:443
    volume:
      - /var/run/docker.sock:/tmp/docker.sock
      - /index/certs:/etc/nginx/certs
- name: Add NGiNX to Systemd
  become: yes
  vars:
    name: proxy
    description: NGiNX Reverse Proxy Container
  template:
    src: podman.service.j2
    dest: /etc/systemd/system/proxy.service
    owner: root
    group: root
    mode: 644

