- name: Install Podman
  become: yes
  dnf:
    name:
      - podman
      - podman-docker
    state: latest
- name: Launch Podman socket
  become: yes
  systemd:
    name: podman.socket
    state: started
    enabled: yes
- name: Create certificates folder
  become: yes
  file:
    path: /index/certs
    mode: '0755'
    state: directory
    owner: root
- name: Create virtual hosts folder
  become: yes
  file:
    path: /index/vhost
    mode: '0755'
    state: directory
    owner: root
- name: Create static HTML folder
  become: yes
  file:
    path: /index/html
    mode: '0755'
    state: directory
    owner: root
- name: Create static ACME folder
  become: yes
  file:
    path: /index/acme
    mode: '0755'
    state: directory
    owner: root
- name: Setup NGiNX reverse proxy
  become: yes
  containers.podman.podman_container:
    name: proxy
    image: docker.io/jwilder/nginx-proxy
    tty: yes
    publish:
      - 80:80
      - 443:443
    volume:
      - /var/run/docker.sock:/tmp/docker.sock:z
      - /index/certs:/etc/nginx/certs
      - /index/vhost:/etc/nginx/vhost.d
      - /index/html:/usr/share/nginx/html
- name: "ACME Companion: Automatic certificate generation"
  become: yes
  containers.podman.podman_container:
    name: acme
    image: docker.io/nginxproxy/acme-companion
    volumes_from:
      - proxy
    volume:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /index/acme:/etc/acme.sh
    env:
      DEFAULT_EMAIL: "{{ email }}"

- name: Add NGiNX to Systemd
  become: yes
  vars:
    name: proxy
    description: NGiNX Reverse Proxy Container
  template:
    src: podman.service.j2
    dest: /etc/systemd/system/proxy.service
    owner: root
    group: root
    mode: 644
- name: Enable service
  become: yes
  systemd:
    name: proxy.service
    state: started
    enabled: yes

