- name: Create Database
  mysql_db:
    name: "{{ DB_NAME }}"
    state: present
- name: Create Database user
  mysql_user:
    name: "{{ DB_USER }}"
    password: "{{ DB_PASSWORD }}"
    state: present
    priv: "{{DB_NAME}}.*:ALL"